insert into catalog (name, category, icon, is_global) values

-- Produce
('Onion',			'Produce',				'🧅',	true),
('Garlic',			'Produce',				'🧄',	true),
('Tomato',			'Produce',				'🍅',	true),
('Potato',			'Produce',				'🥔',	true),
('Lemon',			'Produce',				'🍋',	true),
('Ginger',			'Produce',				'🫚',	true),
('Coriander',		'Produce',				'🌿',	true),
('Spinach',			'Produce',				'🥬',	true),
('Carrot',			'Produce',				'🥕',	true),
('Capsicum',		'Produce',				'🫑',	true),
('Green Chilli',	'Produce',				'🌶️',	true),
('Cucumber',		'Produce',				'🥒',	true),
('Broccoli',		'Produce',				'🥦',	true),
('Cauliflower',		'Produce',				'🥦',	true),
('Peas',			'Produce',				'🫛',	true),
('Corn',			'Produce',				'🌽',	true),
('Mushroom',		'Produce',				'🍄',	true),
('Beetroot',		'Produce',				'🫀',	true),
('Sweet Potato',	'Produce',				'🍠',	true),
('Banana',			'Produce',				'🍌',	true),
('Apple',			'Produce',				'🍎',	true),
('Mango',			'Produce',				'🥭',	true),
('Grapes',			'Produce',				'🍇',	true),
('Watermelon',		'Produce',				'🍉',	true),
('Orange',			'Produce',				'🍊',	true),
('Pomegranate',		'Produce',				'❤️',	true),
('Papaya',			'Produce',				'🍈',	true),
('Pineapple',		'Produce',				'🍍',	true),
('Avocado',			'Produce',				'🥑',	true),

-- Dairy & Eggs
('Milk',			'Dairy & Eggs',			'🥛',	true),
('Paneer',			'Dairy & Eggs',			'🧀',	true),
('Curd / Yogurt',	'Dairy & Eggs',			'🥣',	true),
('Butter',			'Dairy & Eggs',			'🧈',	true),
('Ghee',			'Dairy & Eggs',			'🧈',	true),
('Cream',			'Dairy & Eggs',			'🥛',	true),
('Cheese',			'Dairy & Eggs',			'🧀',	true),
('Eggs',			'Dairy & Eggs',			'🥚',	true),

-- Bakery
('Bread',			'Bakery',				'🍞',	true),
('Whole Wheat Bread','Bakery',				'🍞',	true),
('Buns',			'Bakery',				'🥖',	true),
('Pav',				'Bakery',				'🥖',	true),

-- Meat & Seafood
('Chicken',			'Meat & Seafood',		'🍗',	true),
('Mutton',			'Meat & Seafood',		'🥩',	true),
('Fish',			'Meat & Seafood',		'🐟',	true),
('Prawns',			'Meat & Seafood',		'🦐',	true),

-- Frozen
('Frozen Peas',		'Frozen',				'🫛',	true),
('Frozen Corn',		'Frozen',				'🌽',	true),
('Ice Cream',		'Frozen',				'🍨',	true),
('Frozen Fries',	'Frozen',				'🍟',	true),

-- Pantry & Dry Goods
('Atta',			'Pantry & Dry Goods',	'🌾',	true),
('Maida',			'Pantry & Dry Goods',	'🌾',	true),
('Besan',			'Pantry & Dry Goods',	'🌾',	true),
('Rice',			'Pantry & Dry Goods',	'🍚',	true),
('Basmati Rice',	'Pantry & Dry Goods',	'🍚',	true),
('Poha',			'Pantry & Dry Goods',	'🍚',	true),
('Oats',			'Pantry & Dry Goods',	'🥣',	true),
('Semolina / Rava',	'Pantry & Dry Goods',	'🌾',	true),
('Toor Dal',		'Pantry & Dry Goods',	'🫘',	true),
('Moong Dal',		'Pantry & Dry Goods',	'🫘',	true),
('Chana Dal',		'Pantry & Dry Goods',	'🫘',	true),
('Urad Dal',		'Pantry & Dry Goods',	'🫘',	true),
('Rajma',			'Pantry & Dry Goods',	'🫘',	true),
('Chickpeas',		'Pantry & Dry Goods',	'🫘',	true),
('Lentils',			'Pantry & Dry Goods',	'🫘',	true),
('Sugar',			'Pantry & Dry Goods',	'🍬',	true),
('Salt',			'Pantry & Dry Goods',	'🧂',	true),
('Oil',				'Pantry & Dry Goods',	'🫙',	true),
('Mustard Oil',		'Pantry & Dry Goods',	'🫙',	true),
('Coconut Oil',		'Pantry & Dry Goods',	'🫙',	true),
('Olive Oil',		'Pantry & Dry Goods',	'🫙',	true),
('Vinegar',			'Pantry & Dry Goods',	'🫙',	true),
('Soy Sauce',		'Pantry & Dry Goods',	'🫙',	true),
('Tomato Ketchup',	'Pantry & Dry Goods',	'🍅',	true),
('Pasta',			'Pantry & Dry Goods',	'🍝',	true),
('Noodles',			'Pantry & Dry Goods',	'🍜',	true),
('Vermicelli',		'Pantry & Dry Goods',	'🍜',	true),
('Bread Crumbs',	'Pantry & Dry Goods',	'🍞',	true),
('Honey',			'Pantry & Dry Goods',	'🍯',	true),
('Jam',				'Pantry & Dry Goods',	'🍓',	true),
('Peanut Butter',	'Pantry & Dry Goods',	'🥜',	true),
('Coconut Milk',	'Pantry & Dry Goods',	'🥥',	true),
('Canned Tomatoes',	'Pantry & Dry Goods',	'🥫',	true),

-- Spices & Masalas
('Turmeric',		'Spices & Masalas',		'🟡',	true),
('Red Chilli Powder','Spices & Masalas',	'🌶️',	true),
('Cumin Seeds',		'Spices & Masalas',		'🌿',	true),
('Mustard Seeds',	'Spices & Masalas',		'🌿',	true),
('Coriander Powder','Spices & Masalas',		'🌿',	true),
('Garam Masala',	'Spices & Masalas',		'🌿',	true),
('Chana Masala',	'Spices & Masalas',		'🌿',	true),
('Biryani Masala',	'Spices & Masalas',		'🌿',	true),
('Pepper',			'Spices & Masalas',		'🧂',	true),
('Cardamom',		'Spices & Masalas',		'🌿',	true),
('Cloves',			'Spices & Masalas',		'🌿',	true),
('Cinnamon',		'Spices & Masalas',		'🌿',	true),
('Bay Leaves',		'Spices & Masalas',		'🌿',	true),
('Asafoetida / Hing','Spices & Masalas',	'🌿',	true),

-- Snacks
('Biscuits',		'Snacks',				'🍪',	true),
('Chips',			'Snacks',				'🍿',	true),
('Namkeen',			'Snacks',				'🥜',	true),
('Nuts & Dry Fruits','Snacks',				'🥜',	true),
('Popcorn',			'Snacks',				'🍿',	true),
('Chocolate',		'Snacks',				'🍫',	true),
('Protein Bar',		'Snacks',				'🍫',	true),

-- Beverages
('Tea',				'Beverages',			'🍵',	true),
('Coffee',			'Beverages',			'☕',	true),
('Juice',			'Beverages',			'🧃',	true),
('Coconut Water',	'Beverages',			'🥥',	true),
('Soda / Soft Drink','Beverages',			'🥤',	true),
('Water Bottles',	'Beverages',			'💧',	true),
('Lassi',			'Beverages',			'🥛',	true),

-- Household & Cleaning
('Dish Soap',		'Household & Cleaning',	'🧴',	true),
('Detergent',		'Household & Cleaning',	'🧺',	true),
('Floor Cleaner',	'Household & Cleaning',	'🫧',	true),
('Toilet Cleaner',	'Household & Cleaning',	'🚽',	true),
('Dustbin Bags',	'Household & Cleaning',	'🗑️',	true),
('Tissue Paper',	'Household & Cleaning',	'🧻',	true),
('Kitchen Towels',	'Household & Cleaning',	'🧻',	true),
('Aluminium Foil',	'Household & Cleaning',	'📦',	true),
('Zip Lock Bags',	'Household & Cleaning',	'📦',	true),

-- Personal Care
('Toothpaste',		'Personal Care',		'🪥',	true),
('Shampoo',			'Personal Care',		'🧴',	true),
('Soap',			'Personal Care',		'🧼',	true),
('Moisturiser',		'Personal Care',		'🧴',	true),
('Sunscreen',		'Personal Care',		'🧴',	true),
('Razor',			'Personal Care',		'🪒',	true),
('Sanitary Pads',	'Personal Care',		'🩹',	true),
('Cotton',			'Personal Care',		'🩹',	true);
