insert into catalog (name, category, icon, is_global) values

-- Produce
('Onion',						'Produce',				'🧅',	true),
('Garlic',						'Produce',				'🧄',	true),
('Tomato',						'Produce',				'🍅',	true),
('Potato',						'Produce',				'🥔',	true),
('Lemon',						'Produce',				'🍋',	true),
('Ginger',						'Produce',				'🫚',	true),
('Coriander',					'Produce',				'🌿',	true),
('Coriander Leaves',			'Produce',				'🌿',	true),
('Curry Leaves',				'Produce',				'🍃',	true),
('Mint Leaves',					'Produce',				'🌿',	true),
('Methi Leaves / Fenugreek',	'Produce',				'🌿',	true),
('Spinach',						'Produce',				'🥬',	true),
('Cabbage',						'Produce',				'🥬',	true),
('Carrot',						'Produce',				'🥕',	true),
('Capsicum',					'Produce',				'🫑',	true),
('Green Chilli',				'Produce',				'🌶️',	true),
('Cucumber',					'Produce',				'🥒',	true),
('Broccoli',					'Produce',				'🥦',	true),
('Cauliflower',					'Produce',				'🥦',	true),
('Peas',						'Produce',				'🫛',	true),
('Corn',						'Produce',				'🌽',	true),
('Mushroom',					'Produce',				'🍄',	true),
('Beetroot',					'Produce',				'🫀',	true),
('Sweet Potato',				'Produce',				'🍠',	true),
('Taro Root / Arbi',			'Produce',				'🥔',	true),
('Radish / Mooli',				'Produce',				'🌱',	true),
('Brinjal / Eggplant',			'Produce',				'🍆',	true),
('Okra / Bhindi',				'Produce',				'🟢',	true),
('Green Beans',					'Produce',				'🫛',	true),
('Cluster Beans / Gavar',		'Produce',				'🫛',	true),
('Flat Beans / Papdi',			'Produce',				'🫛',	true),
('Bottle Gourd / Lauki',		'Produce',				'🥒',	true),
('Ridge Gourd / Turai',			'Produce',				'🥒',	true),
('Bitter Gourd / Karela',		'Produce',				'🥒',	true),
('Ivy Gourd / Tindora',			'Produce',				'🥒',	true),
('Drumstick / Moringa',			'Produce',				'🌿',	true),
('Drumstick Leaves',			'Produce',				'🌿',	true),
('Tamarind',					'Produce',				'🟤',	true),
('Banana',						'Produce',				'🍌',	true),
('Raw Banana',					'Produce',				'🍌',	true),
('Banana Flower',				'Produce',				'🌺',	true),
('Apple',						'Produce',				'🍎',	true),
('Mango',						'Produce',				'🥭',	true),
('Raw Papaya',					'Produce',				'🍈',	true),
('Papaya',						'Produce',				'🍈',	true),
('Grapes',						'Produce',				'🍇',	true),
('Watermelon',					'Produce',				'🍉',	true),
('Orange',						'Produce',				'🍊',	true),
('Pomegranate',					'Produce',				'❤️',	true),
('Pineapple',					'Produce',				'🍍',	true),
('Avocado',						'Produce',				'🥑',	true),
('Strawberry',					'Produce',				'🍓',	true),
('Guava',						'Produce',				'🍐',	true),
('Sapota / Chikoo',				'Produce',				'🍑',	true),
('Jackfruit',					'Produce',				'🍈',	true),
('Lychee',						'Produce',				'🍒',	true),
('Coconut',						'Produce',				'🥥',	true),

-- Dairy & Eggs
('Milk',						'Dairy & Eggs',			'🥛',	true),
('Paneer',						'Dairy & Eggs',			'🧀',	true),
('Curd / Yogurt',				'Dairy & Eggs',			'🥣',	true),
('Butter',						'Dairy & Eggs',			'🧈',	true),
('Ghee',						'Dairy & Eggs',			'🧈',	true),
('Cream',						'Dairy & Eggs',			'🥛',	true),
('Cheese',						'Dairy & Eggs',			'🧀',	true),
('Eggs',						'Dairy & Eggs',			'🥚',	true),
('Buttermilk',					'Dairy & Eggs',			'🥛',	true),
('Condensed Milk',				'Dairy & Eggs',			'🥫',	true),
('Khoya / Mawa',				'Dairy & Eggs',			'🍮',	true),

-- Bakery
('Bread',						'Bakery',				'🍞',	true),
('Whole Wheat Bread',			'Bakery',				'🍞',	true),
('Buns',						'Bakery',				'🥖',	true),
('Pav',							'Bakery',				'🥖',	true),

-- Meat & Seafood
('Chicken',						'Meat & Seafood',		'🍗',	true),
('Mutton',						'Meat & Seafood',		'🥩',	true),
('Fish',						'Meat & Seafood',		'🐟',	true),
('Prawns',						'Meat & Seafood',		'🦐',	true),

-- Frozen
('Frozen Peas',					'Frozen',				'🫛',	true),
('Frozen Corn',					'Frozen',				'🌽',	true),
('Frozen Coconut',				'Frozen',				'🥥',	true),
('Ice Cream',					'Frozen',				'🍨',	true),
('Frozen Fries',				'Frozen',				'🍟',	true),

-- Grains & Flours
('Atta',						'Grains & Flours',		'🌾',	true),
('Maida',						'Grains & Flours',		'🌾',	true),
('Besan',						'Grains & Flours',		'🌾',	true),
('Cornflour',					'Grains & Flours',		'🌽',	true),
('Rice',						'Grains & Flours',		'🍚',	true),
('Basmati Rice',				'Grains & Flours',		'🍚',	true),
('Poha',						'Grains & Flours',		'🍚',	true),
('Oats',						'Grains & Flours',		'🥣',	true),
('Semolina / Rava',				'Grains & Flours',		'🌾',	true),
('Sabudana / Tapioca Pearls',	'Grains & Flours',		'⚪',	true),
('Murmura / Puffed Rice',		'Grains & Flours',		'🍚',	true),
('Pasta',						'Grains & Flours',		'🍝',	true),
('Noodles',						'Grains & Flours',		'🍜',	true),
('Vermicelli',					'Grains & Flours',		'🍜',	true),

-- Dals & Pulses
('Toor Dal',					'Dals & Pulses',		'🫘',	true),
('Moong Dal',					'Dals & Pulses',		'🫘',	true),
('Chana Dal',					'Dals & Pulses',		'🫘',	true),
('Urad Dal',					'Dals & Pulses',		'🫘',	true),
('Rajma',						'Dals & Pulses',		'🫘',	true),
('Chickpeas',					'Dals & Pulses',		'🫘',	true),
('Lentils',						'Dals & Pulses',		'🫘',	true),

-- Pantry & Dry Goods
('Sugar',						'Pantry & Dry Goods',	'🍬',	true),
('Salt',						'Pantry & Dry Goods',	'🧂',	true),
('Oil',							'Pantry & Dry Goods',	'🫙',	true),
('Mustard Oil',					'Pantry & Dry Goods',	'🫙',	true),
('Coconut Oil',					'Pantry & Dry Goods',	'🫙',	true),
('Olive Oil',					'Pantry & Dry Goods',	'🫙',	true),
('Vinegar',						'Pantry & Dry Goods',	'🫙',	true),
('Soy Sauce',					'Pantry & Dry Goods',	'🫙',	true),
('Tomato Ketchup',				'Pantry & Dry Goods',	'🍅',	true),
('Bread Crumbs',				'Pantry & Dry Goods',	'🍞',	true),
('Honey',						'Pantry & Dry Goods',	'🍯',	true),
('Jam',							'Pantry & Dry Goods',	'🍓',	true),
('Peanut Butter',				'Pantry & Dry Goods',	'🥜',	true),
('Coconut Milk',				'Pantry & Dry Goods',	'🥥',	true),
('Canned Tomatoes',				'Pantry & Dry Goods',	'🥫',	true),
('Baking Soda',					'Pantry & Dry Goods',	'🧪',	true),
('Baking Powder',				'Pantry & Dry Goods',	'🧪',	true),
('Dry Coconut / Copra',			'Pantry & Dry Goods',	'🥥',	true),
('Kokum',						'Pantry & Dry Goods',	'🍇',	true),

-- Spices & Masalas
('Turmeric',					'Spices & Masalas',		'🟡',	true),
('Red Chilli Powder',			'Spices & Masalas',		'🌶️',	true),
('Dry Red Chillies',			'Spices & Masalas',		'🌶️',	true),
('Cumin Seeds',					'Spices & Masalas',		'🌿',	true),
('Mustard Seeds',				'Spices & Masalas',		'🌿',	true),
('Coriander Powder',			'Spices & Masalas',		'🌿',	true),
('Fennel Seeds / Saunf',		'Spices & Masalas',		'🌿',	true),
('Fenugreek Seeds / Methi Dana','Spices & Masalas',		'🌿',	true),
('Ajwain / Carom Seeds',		'Spices & Masalas',		'🌿',	true),
('Kasuri Methi',				'Spices & Masalas',		'🌿',	true),
('Garam Masala',				'Spices & Masalas',		'🌿',	true),
('Chana Masala',				'Spices & Masalas',		'🌿',	true),
('Chaat Masala',				'Spices & Masalas',		'🌿',	true),
('Pav Bhaji Masala',			'Spices & Masalas',		'🌿',	true),
('Sambar Masala',				'Spices & Masalas',		'🌿',	true),
('Biryani Masala',				'Spices & Masalas',		'🌿',	true),
('Amchur / Dry Mango Powder',	'Spices & Masalas',		'🥭',	true),
('Pepper',						'Spices & Masalas',		'🧂',	true),
('Cardamom',					'Spices & Masalas',		'🌿',	true),
('Cloves',						'Spices & Masalas',		'🌿',	true),
('Cinnamon',					'Spices & Masalas',		'🌿',	true),
('Bay Leaves',					'Spices & Masalas',		'🌿',	true),
('Saffron / Kesar',				'Spices & Masalas',		'🟡',	true),
('Nutmeg / Jaiphal',			'Spices & Masalas',		'🌰',	true),
('Star Anise',					'Spices & Masalas',		'⭐',	true),
('Asafoetida / Hing',			'Spices & Masalas',		'🌿',	true),

-- Nuts & Dry Fruits
('Almonds / Badam',				'Nuts & Dry Fruits',	'🌰',	true),
('Cashews / Kaju',				'Nuts & Dry Fruits',	'🌰',	true),
('Pistachios / Pista',			'Nuts & Dry Fruits',	'🟢',	true),
('Walnuts / Akhrot',			'Nuts & Dry Fruits',	'🌰',	true),
('Peanuts',						'Nuts & Dry Fruits',	'🥜',	true),
('Raisins / Kishmish',			'Nuts & Dry Fruits',	'🍇',	true),
('Dates / Khajoor',				'Nuts & Dry Fruits',	'🟤',	true),
('Figs / Anjeer',				'Nuts & Dry Fruits',	'🍐',	true),
('Makhana / Fox Nuts',			'Nuts & Dry Fruits',	'⚪',	true),

-- Snacks
('Biscuits',					'Snacks',				'🍪',	true),
('Chips',						'Snacks',				'🍿',	true),
('Namkeen',						'Snacks',				'🥜',	true),
('Nuts & Dry Fruits',			'Snacks',				'🥜',	true),
('Popcorn',						'Snacks',				'🍿',	true),
('Chocolate',					'Snacks',				'🍫',	true),
('Protein Bar',					'Snacks',				'🍫',	true),
('Papad',						'Snacks',				'🫓',	true),
('Mathri',						'Snacks',				'🍪',	true),

-- Beverages
('Tea',							'Beverages',			'🍵',	true),
('Coffee',						'Beverages',			'☕',	true),
('Green Tea',					'Beverages',			'🍵',	true),
('Herbal Tea',					'Beverages',			'🍵',	true),
('Juice',						'Beverages',			'🧃',	true),
('Coconut Water',				'Beverages',			'🥥',	true),
('Soda / Soft Drink',			'Beverages',			'🥤',	true),
('Water Bottles',				'Beverages',			'💧',	true),
('Lassi',						'Beverages',			'🥛',	true),
('Rose Syrup / Rooh Afza',		'Beverages',			'🌹',	true),

-- Household & Cleaning
('Dish Soap',					'Household & Cleaning',	'🧴',	true),
('Detergent',					'Household & Cleaning',	'🧺',	true),
('Fabric Softener',				'Household & Cleaning',	'🧺',	true),
('Floor Cleaner',				'Household & Cleaning',	'🫧',	true),
('Toilet Cleaner',				'Household & Cleaning',	'🚽',	true),
('Dustbin Bags',				'Household & Cleaning',	'🗑️',	true),
('Tissue Paper',				'Household & Cleaning',	'🧻',	true),
('Toilet Paper',				'Household & Cleaning',	'🧻',	true),
('Kitchen Towels',				'Household & Cleaning',	'🧻',	true),
('Aluminium Foil',				'Household & Cleaning',	'📦',	true),
('Zip Lock Bags',				'Household & Cleaning',	'📦',	true),
('Scrubber / Sponge',			'Household & Cleaning',	'🧽',	true),
('Air Freshener',				'Household & Cleaning',	'🌸',	true),
('Mosquito Repellent',			'Household & Cleaning',	'🦟',	true),

-- Personal Care
('Toothpaste',					'Personal Care',		'🪥',	true),
('Toothbrush',					'Personal Care',		'🪥',	true),
('Shampoo',						'Personal Care',		'🧴',	true),
('Conditioner',					'Personal Care',		'🧴',	true),
('Soap',						'Personal Care',		'🧼',	true),
('Face Wash',					'Personal Care',		'🧴',	true),
('Moisturiser',					'Personal Care',		'🧴',	true),
('Sunscreen',					'Personal Care',		'🧴',	true),
('Deodorant',					'Personal Care',		'🧴',	true),
('Hair Oil',					'Personal Care',		'🧴',	true),
('Razor',						'Personal Care',		'🪒',	true),
('Sanitary Pads',				'Personal Care',		'🩹',	true),
('Cotton',						'Personal Care',		'🩹',	true);
